package com.ssm.web.mapper;

import com.ssm.web.pojo.HomeworkDetail;
import com.ssm.web.pojo.HomeworkDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeworkDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int countByExample(HomeworkDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int deleteByExample(HomeworkDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int insert(HomeworkDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int insertSelective(HomeworkDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    List<HomeworkDetail> selectByExample(HomeworkDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    HomeworkDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HomeworkDetail record, @Param("example") HomeworkDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HomeworkDetail record, @Param("example") HomeworkDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HomeworkDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HomeworkDetail record);
}