package com.ssm.web.mapper;

import com.ssm.web.pojo.HomeworkScore;
import com.ssm.web.pojo.HomeworkScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HomeworkScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int countByExample(HomeworkScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int deleteByExample(HomeworkScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int insert(HomeworkScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int insertSelective(HomeworkScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    List<HomeworkScore> selectByExample(HomeworkScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    HomeworkScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") HomeworkScore record, @Param("example") HomeworkScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") HomeworkScore record, @Param("example") HomeworkScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HomeworkScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_score
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HomeworkScore record);
}