package com.ssm.web.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;


public class Homework {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.teacher
     *
     * @mbggenerated
     */
    private Integer teacher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.contains
     *
     * @mbggenerated
     */
    private String contains;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.assign_time
     *
     * @mbggenerated
     */

    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date assignTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.id
     *
     * @return the value of homework.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.id
     *
     * @param id the value for homework.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.teacher
     *
     * @return the value of homework.teacher
     *
     * @mbggenerated
     */
    public Integer getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.teacher
     *
     * @param teacher the value for homework.teacher
     *
     * @mbggenerated
     */
    public void setTeacher(Integer teacher) {
        this.teacher = teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.contains
     *
     * @return the value of homework.contains
     *
     * @mbggenerated
     */
    public String getContains() {
        return contains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.contains
     *
     * @param contains the value for homework.contains
     *
     * @mbggenerated
     */
    public void setContains(String contains) {
        this.contains = contains == null ? null : contains.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.assign_time
     *
     * @return the value of homework.assign_time
     *
     * @mbggenerated
     */

    public Date getAssignTime() {
        return assignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.assign_time
     *
     * @param assignTime the value for homework.assign_time
     *
     * @mbggenerated
     */

    public void setAssignTime(Date assignTime) {
        this.assignTime = assignTime;
    }
}