package com.ssm.web.pojo;

public class HomeworkScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_score.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_score.scorer
     *
     * @mbggenerated
     */
    private Integer scorer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_score.score
     *
     * @mbggenerated
     */
    private String score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_score.id
     *
     * @return the value of homework_score.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_score.id
     *
     * @param id the value for homework_score.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_score.scorer
     *
     * @return the value of homework_score.scorer
     *
     * @mbggenerated
     */
    public Integer getScorer() {
        return scorer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_score.scorer
     *
     * @param scorer the value for homework_score.scorer
     *
     * @mbggenerated
     */
    public void setScorer(Integer scorer) {
        this.scorer = scorer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_score.score
     *
     * @return the value of homework_score.score
     *
     * @mbggenerated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_score.score
     *
     * @param score the value for homework_score.score
     *
     * @mbggenerated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }
}