package com.ssm.web.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;


import java.util.Date;

public class HomeworkDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_detail.submit_time
     *
     * @mbggenerated
     */

    @JsonFormat(locale="zh", timezone="GMT+8", pattern="yyyy-MM-dd HH:mm:ss")
    private Date submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_detail.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_detail.submitter
     *
     * @mbggenerated
     */
    private Integer submitter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_detail.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_detail.homework
     *
     * @mbggenerated
     */
    private Integer homework;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_detail.id
     *
     * @return the value of homework_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_detail.id
     *
     * @param id the value for homework_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_detail.submit_time
     *
     * @return the value of homework_detail.submit_time
     *
     * @mbggenerated
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_detail.submit_time
     *
     * @param submitTime the value for homework_detail.submit_time
     *
     * @mbggenerated
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_detail.details
     *
     * @return the value of homework_detail.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_detail.details
     *
     * @param details the value for homework_detail.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_detail.submitter
     *
     * @return the value of homework_detail.submitter
     *
     * @mbggenerated
     */

    public Integer getSubmitter() {
        return submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_detail.submitter
     *
     * @param submitter the value for homework_detail.submitter
     *
     * @mbggenerated
     */

    public void setSubmitter(Integer submitter) {
        this.submitter = submitter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_detail.score
     *
     * @return the value of homework_detail.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_detail.score
     *
     * @param score the value for homework_detail.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_detail.homework
     *
     * @return the value of homework_detail.homework
     *
     * @mbggenerated
     */
    public Integer getHomework() {
        return homework;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_detail.homework
     *
     * @param homework the value for homework_detail.homework
     *
     * @mbggenerated
     */
    public void setHomework(Integer homework) {
        this.homework = homework;
    }
}